#!/bin/bash

function testhelp {
    #TEST

    echo
#    echo "TEST USAGE"
    echo "Usage:"
    echo "$0 test [tested cpp file] [options]"
    echo "Options:"
    echo "-d [test dir] - directory with tests (input - .in, output - .out)"
    echo "-t [test file] - single file with test. -ow and -cmo will not work with single test file (use -d)"
    echo "-c [cpp file] - if no .out files are present generate outputs with this program"
    echo "-ow - overwrite existing .out and create missing files with -c program"
    echo "-tl [time in s] - time limit"
    echo "-ml [memory in MB] - memory limit"
    echo "-tlf - time limit specified in first line of each file with test NOT IMPELMENTED"
    echo "-pd - print diff for failed tests"
    echo "-tf - check only tests which name starts with tested cpp file name"
    echo "-q - quiet operation"
    echo "-san - use sanitizer"
    echo "-cc [cpp file] - use custom checker. (takes test and answer appended as input, returns 0 if correct, other - wa)"
    echo "-oc - ignore existing .out and generate outputs with -c program (without overwritting)"
    echo "-cmo - generate only missing .out files with -c program"
    echo "-oif - use oi test format (.in in in/ subdir and .out in out/)"
    echo "-cf - copy test files to temp dir instead of soft linking"
    echo "-ban - banner status"
    exit 0
}
#GEN
function genhelp {
    echo
#    echo "GEN USAGE"
    echo "Usage:"
    echo "$0 gen [tested cpp file] [compare cpp file] [generator cpp file] [options]"
    echo "Options:"
    echo "-mt - max number of test to generate"
    echo "-mf - number of failed tests to generate"
    echo "-s - save failed tests"
    echo "-oit - generate tests as .in and .out files for use with \"oic test\", ignore testing and all flags except -D and -mt (numer of tests to generate)"
    echo "-D [macro] - macro to compile test generator ex. -D QNUM=1"
    echo "-pd - print diff for failed tests"
    echo "-cc [cpp file] - use custom checker. (takes test and answer appended as input, returns 0 if correct, other - wa)"
    echo "-san - use sanitizer"
    exit 0
}

echo "+--------------------------+"
echo "|     OI CHECK SUITE       |"
echo "|        BY PIOTRO         |"
echo "|   OICT v1.1  OICG v1.0   |"
echo "+--------------------------+"
echo

if [ "$1" = test ]; then
    shift
    ./oict.sh $*
    ret=$?
    [ $ret = 2 ] && testhelp
    exit $ret
elif [ "$1" = gen ]; then
    shift
    ./oicg.sh $*
    ret=$?
    [ $ret = 2 ] && genhelp
    exit $ret
fi

echo "Usage:"
echo "$0 test - test program with known tests (correct, time, exceptions, memory)"
echo "$0 gen  - simple test of program with tests generated by testgen"
echo "$0 test --help / $0 gen --help - display help for test or gen programs"

